version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npx", "http-server", "-p", "3000"]
  weather-api:
    build:
      context: ./weather-api
    ports:
      - "5000:5000"
  location-service:
    build:
      context: ./location-service
    ports:
      - "8080:6000"  # Updated port to match Flask app
